// <auto-generated />
using System;
using AID.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AID.Migrations
{
    [DbContext(typeof(DContext))]
    partial class DContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AID.Models.charity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("charity");
                });

            modelBuilder.Entity("AID.Models.config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloseWeekDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseYearDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("configs");
                });

            modelBuilder.Entity("AID.Models.login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("login");
                });

            modelBuilder.Entity("AID.Models.patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("AID.Models.visit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("charityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("discountValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("insurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("patientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("visitDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("visitTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("visits");
                });
#pragma warning restore 612, 618
        }
    }
}
